#!/bin/perl

# ********************************************************************
# Script Name:   perms
# Author:        emarfah
# Function:      To perform permissions updates on relevant files
#                 
# ********************************************************************

# ********************************************************************
# 	File Declarations
#
# ********************************************************************

$CWD=`pwd`;
my $PERMS_FILE;
my $SCRIPTNAME=$0;

# Check for the Arguments passed to the Script
if ($ARGV[0]){
	$PERMS_FILE=$ARGV[0];
}
else{
	error("No Arguments given to this script!", __LINE__);
}

# ********************************************************************
# 	Functions
#
# ********************************************************************

#.....................................................................
#  Function Name:  update_perms
#  Function Desc:  Updates the permissions on all files
#.....................................................................
sub update_perms()
{
	# Open info file with all the tr cr and wp information
        if (!(open(PERMISSIONS, "$PERMS_FILE")))
        {
                error("Can't open file:$PERMS_FILE $!", __LINE__);
                return;
        }
        while (<PERMISSIONS>)
	{
		my ($filename, $user, $group, $perms) = split(/ /,$_);
		chomp $filename;
		chomp $user;
		chomp $group;
		chomp $perms;
		if ($filename !~ /##/){
			if ($filename ne ""){
				#print "Changing ownership, group and permissions on $filename  \n";
				`chown $user $filename`;
				`chgrp $group $filename`;
				`chmod $perms $filename`;
			}
		}
	}
	close(PERMISSIONS);
}

#.....................................................................
#  Function Name:  cleanup
#  Function Desc:  The very last function of the script. 
#                 
#  Return:         1 or 0
#.....................................................................
sub cleanup()
{
	# Cleanup anything that needs cleaning
	exit();
} 

#..........................................
#  Function Name:  usage
#  Function Desc:  Display user help
#  Return:         0
#..........................................
sub usage
{
	print("Usage: $SCRIPTNAME <permission_file>\n\n" );
	print("  -help		:    Prints this message \n"  );
	exit;
}

#..........................................
#  Function Name:  error
#  Function Desc:  Show a uniform modern error message
#  Return:         1
#..........................................
sub error
{
    $ERROR = $_[0] ;                   # $HEADER is the first string past to the header function
    $LINE_NUMBER=$_[1] ;            # __LINE__ is the Line number of a prog.

    print "------------------------------------------------------------------------------\n";
    print "  ERROR!\t$ERROR \n";
    print "  Line Number:\t$LINE_NUMBER \n";
    print "------------------------------------------------------------------------------\n";
    exit 1;

}

#-------------------------------------------------------------------
#MAIN
#-------------------------------------------------------------------
update_perms();
cleanup();
